# https://taskfile.dev
version: '3'

tasks:
  build:
    cmds:
      - go build -o out/dojo ./cmd/dojo/main.go

  fmt:
    cmds:
      - go fmt ./...

  lint:
    cmds:
      - golangci-lint run

  lint:fix:
    cmds:
      - golangci-lint run --fix

  test:
    cmds:
      - go test ./...

  e2e:
    deps:
      - build
    env:
      DOJO_BIN: "{{.TASKFILE_DIR}}/out/dojo"
    cmds:
      - go test -tags=e2e ./test/e2e
      - go test -tags=e2e ./test/e2e/world